name: Build Android APK
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROIDSDK_ROOT: ${{ runner.tool_cache }}/Android/Sdk

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install apt dependencies
        run: sudo apt-get update && sudo apt-get install -y \
              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
              libgl1-mesa-dev libgles2-mesa-dev zlib1g-dev libfreetype6-dev

      - name: Set up Android SDK & NDK
        uses: subosito/android-sdk@2.1.1
        with:
          api-level: 33
          build-tools: '33.0.2'
          ndk: '25b'

      - name: Install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install Cython==0.29.33 buildozer

      - name: Build APK
        run: buildozer android debug --verbose < /dev/null

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyCaptchaApp-APK
          path: bin/**/*.apk
