name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout الكود
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Buildozer Action
      #    هذه Action تتولى تثبيت Buildozer وكل المتطلبات وتشغيل الأمر المحدد
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          # مسار المجلد الذي فيه buildozer.spec ('.' يعني جذر المستودع)
          workdir: .
          # الأمر الذي تريد تشغيله (يمكن تغييره لـ 'android release' وهكذا)
          command: buildozer android debug
          # إصدار Buildozer: 'stable' يثبت آخر إصدار متاح من PyPI
          buildozer_version: stable

      # 3. رفع الـ APK كـ Artifact (الإصدار الرابع)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          # الاسم الظاهر في تبويب Artifacts
          name: MyCaptchaApp-APK
          # مسار الملف المنتج، يُستخرج تلقائيًا من مخرجات الخطوة السابقة
          path: ${{ steps.buildozer.outputs.filename }}
