name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf automake libtool m4 \
            zlib1g-dev libncurses-dev \
            cmake libffi-dev libssl-dev

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer & dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install Cython==0.29.33 buildozer

      - name: Build APK with Buildozer
        run: buildozer android debug --verbose < /dev/null

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCaptchaApp-APK
          path: bin/android/debug/*.apk
